export const PRODUCT_LIST_REQUEST = 'PRODUCTR_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCTR_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCTR_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCTR_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCTR_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCTR_DETAILS_FAIL';
